function [BW_out,properties] = Filter3MaskRegions(BW_in)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 25-Feb-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
BW_out = bwpropfilt(BW_out,'Area',[20000, 25000]);
% Get properties.
properties = regionprops(BW_out, {'Area','Eccentricity'});
properties = struct2table(properties);
end
