function [BW,maskedImage] = erosion(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 26-Feb-2023
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(im2gray(X));

% Erode mask with default
radius = 15;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);
BW = imclose(BW,se);


% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

